### ISSUE TITLE
Move content of InitialDraft.md and List_of_BBox_Standards.md

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/Bounding-Box-Abstract-Specification#1]
The metanorma-based document has been [created](https://github.com/opengeospatial/Bounding-Box-Abstract-Specification/tree/main/abstract_specification_topic). Please move the contents of [InitialDraft.md](https://github.com/opengeospatial/Bounding-Box-Abstract-Specification/blob/main/InitialDraft.md) and [List_of_BBox_Standards.md](https://github.com/opengeospatial/Bounding-Box-Abstract-Specification/blob/main/List_of_BBox_Standards.md) to the metanorma-based document.

**Comment by chris-little** [comment]
@ghobona @samadammeek Done, but I may have not made best use of metanorma formatting. I have also requested a doc number OGC 22-027
